name: test, build, deploy mvc in main server 
on:
  push:
    branch:
      -main
jobs:
  build_docker:
    name: build and push to docker hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build -t (nama repository) .
    -  name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name : push to docker
      run: docker push (nama repository)
    
  deploy: 
    name: deployment  to EC2 server
      runs-on: ubuntu-latest
      needs: build_docker
      steps:
        - uses: actions/checkout@v3
        - name: login to EC2  
          env:
            SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            SSH_HOST: ${{secrets.SSH_HOSTNAME}}
            SSH_USER: ${{secrets.SSH_USER_NAME}}
          run: |
          # mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/(nama repository).pem
          chmod 400 ~/.ssh/(nama repository).pem
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/(nama sepository).pem
            StrictHostKeyChecking=no
          END
        - name: login EC2 + docker pull + running container
          run: ssh staging 'docker rm -f $(docker ps -a -q) && docker pull (nama repository) && docker run -d -p 8000:8000 --name simpe-mvc-apps (nama repository)'
        
    